---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-1
  labels:
    name: zookeeper-1
    service: zookeeper
    zookeeper_id: "1"
spec:
#  type: ClusterIP
#  clusterIP: 10.200.10.31
  type: LoadBalancer
  ports:
    - name: client
      port: 2181
    - name: follower
      port: 2888
    - name: election
      port: 3888
  selector:
    name: zookeeper-1
    zookeeper_id: "1"
